language: python
python:
  - pypy
env:
  - PORTAGE_VER="2.2.26"
script:
  - env | sort
  - echo "all good"

notifications:
  irc:
    channels: "chat.freenode.net#not-your-server.de"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}) - %{author}: %{commit_subject}"
      - "%{message} - Build details : %{build_url}"
    use_notice: true